# Utilizando sintax da versão 2:root
#   https://docs.docker.com/compose/compose-file/#/versioning
version: '2'

services:
###########################
# Container Web (Nginx)
###########################
    nginx:
        image: nginx:latest
        container_name: server-nginx
        ports:
            - 80:80
            #- 8080:80
        volumes:
            - ./nginx:/etc/nginx/conf.d
        volumes_from:
            - workspace

###########################
# Container PHP
###########################
    workspace:
        image: rocharor/workspace
        container_name: workspace
        expose:
            - 9000
        volumes:
            - ../:/var/www/html

###########################
# Container de banco de dados (MySQL)
###########################
    mysql:
        image: mysql:latest
        container_name: server-mysql
        ports:
          - "3306:3306"
        volumes:
            - ./mysql/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: xxx
            MYSQL_USER: xxx
            MYSQL_PASSWORD: xxx
